// apps/dashboard/web/src/apps/dashboard/views/quickstart/components/PostmanSource.vue
<template>
    <div>
        Use postman to send traffic to Akto and realize quick value. If you like what you see, we highly recommend using AWS or GCP traffic mirroring to get real user data for a smooth, automated and minimum false positive experience.
    </div>
</template>

<script>
export default {
    name: "PostmanSource"
}
</script>

<style lang="sass" scoped>
.clickable-docs
    cursor: pointer
    color: #6200B0 !important
    text-decoration: underline 
</style>

// apps/dashboard/web/src/apps/dashboard/pages/quick_start/components/PostmanSource.jsx
import { RadioButton, Text } from '@shopify/polaris'
import React, { useState } from 'react'

function PostmanSource() {

    const [type, setType] = useState("api")
    const handleChange = (val) => {
        setType(val)
    }

    return (
        <div style={{marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '20px'}}>
            <Text variant='bodyMd'>
                Use postman to send traffic to Akto and realize quick value. If you like what you see, we highly recommend using AWS or GCP traffic mirroring to get real user data for a smooth, automated and minimum false positive experience.
            </Text>

            <div style={{display: 'flex', flexDirection: 'column', gap: '4px'}}>
                <RadioButton id="api" label="Import using postman API key" checked={type === "api"} onChange={()=>handleChange("api")}/>
                <RadioButton id="collection" label="Import using postman collection file" checked={type === "collection"} onChange={()=>handleChange("collection")}/>
            </div>
        </div>
    )
}

export default PostmanSource
