// apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/shared/DonutChart.jsx
import React from 'react'
import HighchartsReact from "highcharts-react-official"
import Highcharts from "highcharts"
import { useRef } from "react";

function DonutChart({data, title, size}) {
    const chartComponentRef = useRef(null)

    const seriesData = Object.keys(data).map((ele)=>{
        return{
            name: ele,
            y: data[ele].text,
            color: data[ele].color,
        }
    })

    const chartOptions = {
        chart:{
            type: 'pie',
            height: size + 10,
            width: size,
            className: 'pie-chart',
            margin: '10'
        },
        credits:{
            enabled: false,
        },
        title:{
            text: title,
            y: size*0.4,
        },
        tooltip: {
            backgroundColor: {
                linearGradient: [0, 0, 0, 60],
                stops: [
                    [0, '#FFFFFF'],
                    [1, '#E0E0E0']
                ]
            },
            borderWidth: 1,
            borderColor: '#AAA'
        },
        plotOptions: {
            pie: {
              size: (size+'px'),
              innerSize: '60%',
              dataLabels: {
                enabled: false
              }
            }
        },
        series:[{
            data: seriesData,
            colorByPoint: true,
            states: {
                inactive: {
                    opacity: 1
                }
            }
        }]
    }

    return (
        <HighchartsReact 
            highcharts={Highcharts} 
            options={chartOptions} 
            ref={chartComponentRef}
        />
    )
}

export default DonutChart

// apps/dashboard/web/src/apps/dashboard/shared/components/DonutChart.vue
<template>
  <div>
    <chart :options="chartOptions()" :updateArgs="[true, false]" ref='highcharts'/>
  </div>
</template>

<script>
import obj from "@/util/obj"
import {Chart} from 'highcharts-vue'

export default {

  name: "DonutChart",
  components: {
    Chart
  },
  props: {
      data: obj.arrR,
      name: obj.strR,
      size: obj.numR
  },
  methods: {
    chartOptions () {
      return  {
        chart: {
          type: 'pie',
          height: this.size + 3,
          width: this.size,
          marginTop: 12
        },
        title: {
          text: (this.data || []).reduce((z, e) => z + e.y, 0),
          y: 100
        },
        subtitle: {
          text: this.name,
          y: 120
        },
        tooltip: {
          enabled: false
        },
        plotOptions: {
          pie: {
            size: (this.size+'px'),
            borderWidth: (this.data && this.data.length > 1) ? 3 : 0,
            innerSize: '80%',
            dataLabels: {
              enabled: false
            }
          }
        },
        series:[{
          enableMouseTracking: false,
          name: this.name,
          colorByPoint: true,
          data: this.data
        }]
      }
    }
  }
}
</script>

<style scoped lang="sass">
</style>
