// apps/dashboard/web/polaris_web/web/src/apps/dashboard/components/charts/LineChart.jsx
import HighchartsReact from "highcharts-react-official"
import Highcharts from "highcharts"
import { useEffect, useRef, useState } from "react";
import func from "../../../../util/func";
import SpinnerCentered from "../progress/SpinnerCentered";

function LineChart(props) {

    const { type, height, backgroundColor, data, graphPointClick, tooltipFormatter, yAxisTitle, title, text, defaultChartOptions, areaFillHex, color, width, noGap, showGridLines } = props;
    const chartComponentRef = useRef(null)

    const fillColor = {
        linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
        stops: [
            [0, color],
            [1, '#000000'],
        ],
    };

    const coreChartOptions = {
        chart: {
            type: type,
            height: (height) + 'px',
            spacing: [5, 0, 0, 0],
            backgroundColor: backgroundColor
        },
        credits: {
            enabled: false,
        },
        title: {
            text: title,
            align: 'left',
            margin: 20
        },
        tooltip:{
            shared: false,
        },
        plotOptions: {
            column: {
                dataLabels: {
                    enabled: true
                }
            },
            series: {
                minPointLength: noGap ? 0 : 5,
                pointWidth: width,
                cursor: 'pointer',
                point: {
                    events: {
                        click: () => {
                        }
                    }
                }
            }
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: {
                day: '%b %e',
                month: '%b',
            },
            title: {
                text: 'Date',
            },
            visible: text,
            gridLineWidth: 0,
        },
        yAxis: [
            {
                title: {
                    text: yAxisTitle,
                },
                visible: text,
                gridLineWidth: showGridLines ? 1 : 0,
                min: 1,
            }
        ],
        time: {
            useUTC: false
        },
        ...defaultChartOptions
    }

    function processChartData(data) {
        return  data.map((x, i) => {
            return {
                data: x.data,
                color: x.color,
                name: x.name,
                fillColor: areaFillHex ? fillColor : {},
                marker: {
                    enabled: false
                },
                yAxis: i==1 ? 1 : 0,
                lineWidth: i==1 ? 1: 3

            }
        })
    }

    const [chartOptions, setChartOptions] = useState({...coreChartOptions, series: []});

    useEffect(() => {
        setChartOptions((prev) => {
            let tmp = processChartData(data);
            if (func.deepComparison(prev.series, tmp)) {
                return prev;
            }
            prev.series = tmp;
            prev.yAxis = tmp.map((x, i) => {
                return {
                    title: {
                        text: x.name,
                        color: x.color
                    },
                    visible: x.name,
                    gridLineWidth: 1,
                    min: 1,
                    opposite: i==1,
                }
            })
            prev.plotOptions.series.point.events.click = graphPointClick
            prev.tooltip.formatter = tooltipFormatter
            return {...prev};
        })
    }, [data])

    return (
        data.length > 0 ? <HighchartsReact
        key={"chart"}
        highcharts={Highcharts}
        options={chartOptions}
        ref={chartComponentRef}
    /> : <SpinnerCentered/>
    )
}

export default LineChart;

// apps/dashboard/web/src/apps/dashboard/shared/components/LineChart.vue
<template>
  <chart
      :options="chartOptions"
      :updateArgs="[true, false]"
      ref='highcharts'
      v-if="(data && data.length > 0) || (inputMetrics && inputMetrics.length > 0)"
  />
  <div v-else class="no-data-chart">
    No trend data!
  </div>
</template>

<script>
import merge from "@/util/merge";
import obj from "@/util/obj";
import {Chart} from "highcharts-vue"
import func from "@/util/func";

export default {
  name: "LineChart",
  props: {
    type: obj.strR,
    color: obj.strR,
    areaFillHex: obj.boolR,
    title: obj.strR,
    data: obj.arrR,
    height: obj.numR,
    defaultChartOptions: obj.objR,
    backgroundColor: {
      type: String,
      default: "#FFFFFF"
    },
    text: obj.boolR,
    inputMetrics: {
      type: Array,
      default: function () {
        return []
      }
    }
  },
  components: {
    Chart
  },
  computed: {
    chartOptions: {
      get: function () {

        var fillColor = {
          linearGradient: {x1:0, y1:0, x2:0, y2:1},
          stops: [
            [0, this.color+"3b"],
            [1, "#FFFFFF"]
          ]
        }

        var basicOpts = {
          chart: {
            type: this.type,
            height: (this.height)+'px',
            spacing: [5,0,0,0],
            backgroundColor: this.backgroundColor
          },
          title: {
            text: '',
            style: {
              "text-align": "left"
            }
          },
          tooltip: {
            shared: true
          },
          series: [
            {
              data: this.data,
              color: this.color,
              name: this.title,
              fillColor: this.areaFillHex ? fillColor : {},
              marker: {
                enabled: this.data.length <= 2
              },
              yAxis: 0
            },
            ...this.inputMetrics.map((x, i) => {
              return {
                data: x.data,
                color: "#FF4DCA",
                name: x.name,
                marker: {
                  enabled: false,
                  symbol: 'circle'
                },
                fillColor: {
                  linearGradient: {x1:0, y1:0, x2:0, y2:1},
                  stops: [
                    [0, "#FFFFFF"],
                    [1, "#FFFFFF"]
                  ]
                },
                yAxis: (i+1)
              }
            })
          ],
          xAxis: [
            {
              type: 'datetime',
              dateTimeLabelFormats: {
                day: '%b \ %e',
                month: '%b'
              },
              title: 'Date',
              visible: this.text,
              gridLineWidth: '0px'
            }
          ],
          yAxis: [
              {
                title: this.title,
                visible: this.text,
                gridLineWidth: '0px',
                min : 0
              },
              ...this.inputMetrics.map((x,i) => {
                return {
                  title: '',
                  visible: true,
                  opposite: true,
                  min : 0
                }
              })
          ],
          legend: {
            enabled: false
          }
        }

        return merge.deepmerge(basicOpts, this.defaultChartOptions)
      },
      set: function (newVal) {
        if (this.$refs.highcharts) {
          this.$refs.highcharts.chart.update(newVal)
        }
      }
    }
  }
}
</script>

<style scoped lang="sass">
.no-data-chart
  color: #d2d3d4
  font-size: 18px
</style>
