// apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/observe/api_collections/ApiEndpoints.jsx
import PageWithMultipleCards from "../../../components/layouts/PageWithMultipleCards"
import { Text, HorizontalStack, Button, Box, Popover, IndexFiltersMode, VerticalStack, TextField, Modal } from "@shopify/polaris"
import api from "../api"
import { useEffect, useState } from "react"
import func from "@/util/func"
import GithubSimpleTable from "../../../components/tables/GithubSimpleTable";
import { useParams } from "react-router-dom"
import { saveAs } from 'file-saver'

import "./api_inventory.css"
import ApiDetails from "./ApiDetails"
import UploadFile from "../../../components/shared/UploadFile"
import RunTest from "./RunTest"
import ObserveStore from "../observeStore"
import SpinnerCentered from "../../../components/progress/SpinnerCentered"
import AktoGptLayout from "../../../components/aktoGpt/AktoGptLayout"
import dashboardFunc from "../../transform"
import settingsRequests from "../../settings/api"
import PersistStore from "../../../../main/PersistStore"
import transform from "../transform"
import { CellType } from "../../../components/tables/rows/GithubRow"
import {ApiGroupModal, Operation} from "./ApiGroupModal"

const headings = [
    {
        text: "Endpoint",
        value: "endpointComp",
        title: "Api endpoints",
    },
    {
        text: "Risk score",
        title: "Risk score",
        value: "riskScoreComp",
    },
    {
        text: "Hostname",
        value: 'hostName',
        title: "Hostname",
        maxWidth: '100px',
        type: CellType.TEXT,
    },
    {
        text: 'Access Type',
        value: 'access_type',
        title: 'Access type',
        showFilter: true,
        type: CellType.TEXT,
    },
    {
        text: 'Auth Type',
        title: 'Auth type',
        value: 'auth_type',
        showFilter: true,
        type: CellType.TEXT,
    },
    {
        text: 'Sensitive Params',
        title: 'Sensitive params',
        value: 'sensitiveTagsComp',
        filterKey: 'sensitiveTags',
        showFilter: true
    },
    {
        text: 'Last Seen',
        title: 'Last seen',
        value: 'last_seen',
        type: CellType.TEXT,
    },
]

let headers =  JSON.parse(JSON.stringify(headings))
headers.push({
    text: "Method",
    value: "method",
    showFilter: true
},)

const sortOptions = [
    { label: 'Risk Score', value: 'riskScore asc', directionLabel: 'Highest', sortKey: 'riskScore'},
    { label: 'Risk Score', value: 'riskScore desc', directionLabel: 'Lowest', sortKey: 'riskScore'},
    { label: 'Method', value: 'method asc', directionLabel: 'A-Z', sortKey: 'method' },
    { label: 'Method', value: 'method desc', directionLabel: 'Z-A', sortKey: 'method' },
    { label: 'Endpoint', value: 'endpoint asc', directionLabel: 'A-Z', sortKey: 'endpoint' },
    { label: 'Endpoint', value: 'endpoint desc', directionLabel: 'Z-A', sortKey: 'endpoint' },
    { label: 'Auth Type', value: 'auth_type asc', directionLabel: 'A-Z', sortKey: 'auth_type' },
    { label: 'Auth Type', value: 'auth_type desc', directionLabel: 'Z-A', sortKey: 'auth_type' },
    { label: 'Access Type', value: 'access_type asc', directionLabel: 'A-Z', sortKey: 'access_type' },
    { label: 'Access Type', value: 'access_type desc', directionLabel: 'Z-A', sortKey: 'access_type' },
    { label: 'Last seen', value: 'lastSeenTs asc', directionLabel: 'Newest', sortKey: 'lastSeenTs' },
    { label: 'Last seen', value: 'lastSeenTs desc', directionLabel: 'Oldest', sortKey: 'lastSeenTs' },
];

function ApiEndpoints() {

    const params = useParams()
    const apiCollectionId = params.apiCollectionId

    const showDetails = ObserveStore(state => state.inventoryFlyout)
    const setShowDetails = ObserveStore(state => state.setInventoryFlyout)
    const collectionsMap = PersistStore(state => state.collectionsMap)

    const pageTitle = collectionsMap[apiCollectionId]

    const [apiEndpoints, setApiEndpoints] = useState([])
    const [apiInfoList, setApiInfoList] = useState([])
    const [unusedEndpoints, setUnusedEndpoints] = useState([])

    const [endpointData, setEndpointData] = useState([])
    const [selectedTab, setSelectedTab] = useState("All")
    const [selected, setSelected] = useState(0)
    const [loading, setLoading] = useState(true)
    const [apiDetail, setApiDetail] = useState({})
    const [exportOpen, setExportOpen] = useState(false)

    const filteredEndpoints = ObserveStore(state => state.filteredItems)
    const setFilteredEndpoints = ObserveStore(state => state.setFilteredItems)

    const [prompts, setPrompts] = useState([])
    const [isGptScreenActive, setIsGptScreenActive] = useState(false)
    const [isGptActive, setIsGptActive] = useState(false)

    const tableTabs = [
        {
            content: 'All',
            index: 0,
            badge: endpointData["All"]?.length?.toString(),
            onAction: ()=> {setSelectedTab('All')},
            id: 'All',
        },
        {
            content: 'New',
            index: 1,
            badge: endpointData["New"]?.length?.toString(),
            onAction: ()=> {setSelectedTab('New')},
            id: 'New',
        },
        {
            content: 'Sensitive',
            index: 2,
            badge: endpointData["Sensitive"]?.length?.toString(),
            onAction: ()=> {setSelectedTab('Sensitive')},
            id:'Sensitive',
        },
        {
            content: 'High risk',
            index: 3,
            badge: endpointData["Risk"]?.length?.toString(),
            onAction: ()=> {setSelectedTab('Risk')},
            id: 'Risk',
        },
        {
            content: 'No auth detected',
            index: 4,
            badge: endpointData["No_auth"]?.length?.toString(),
            onAction: ()=> {setSelectedTab('No_auth')},
            id: 'No_auth'
        },
    ]

    async function fetchData() {
        setLoading(true)
        let apiCollectionData = await api.fetchAPICollection(apiCollectionId)
        let apiEndpointsInCollection = apiCollectionData.data.endpoints.map(x => { return { ...x._id, startTs: x.startTs, changesCount: x.changesCount, shadow: x.shadow ? x.shadow : false } })
        let apiInfoListInCollection = apiCollectionData.data.apiInfoList
        let unusedEndpointsInCollection = apiCollectionData.unusedEndpoints
        let sensitiveParamsResp = await api.loadSensitiveParameters(apiCollectionId)
        let sensitiveParams = sensitiveParamsResp.data.endpoints

        let sensitiveParamsMap = {}
        sensitiveParams.forEach(p => {
            let key = p.method + " " + p.url
            if (!sensitiveParamsMap[key]) sensitiveParamsMap[key] = new Set()

            if (!p.subType) {
                p.subType = { name: "CUSTOM" }
            }

            sensitiveParamsMap[key].add(p.subType)
        })

        apiEndpointsInCollection.forEach(apiEndpoint => {
            apiEndpoint.sensitive = sensitiveParamsMap[apiEndpoint.method + " " + apiEndpoint.url] || new Set()
        })

        let data = {}
        let allEndpoints = func.mergeApiInfoAndApiCollection(apiEndpointsInCollection, apiInfoListInCollection, null)
        const prettifyData = transform.prettifyEndpointsData(allEndpoints)
        data['All'] = prettifyData
        data['Sensitive'] = prettifyData.filter(x => x.sensitive && x.sensitive.size > 0)
        data['Risk'] = prettifyData.filter(x=> x.riskScore >= 4)
        data['New'] = prettifyData.filter(x=> x.isNew)
        data['No_auth'] = prettifyData.filter(x => x.open)
        setEndpointData(data)
        setSelectedTab("All")
        setSelected(0)

        setApiEndpoints(apiEndpointsInCollection)
        setApiInfoList(apiInfoListInCollection)
        setUnusedEndpoints(unusedEndpointsInCollection)

        setLoading(false)
    }

    const checkGptActive = async() => {
        await settingsRequests.fetchAktoGptConfig(apiCollectionId).then((resp) => {
            if(resp.currentState[0].state === "ENABLED"){
                setIsGptActive(true)
            }
        })
    }

    useEffect(() => {
        fetchData()
        checkGptActive()
    }, [])

    const resourceName = {
        singular: 'endpoint',
        plural: 'endpoints',
    };

    const getFilteredItems = (filteredItems) => {
        setFilteredEndpoints(filteredItems)
    }

    function handleRowClick(data) {
        let tmp = { ...data, endpointComp: "", sensitiveTagsComp: "" }
        const sameRow = func.deepComparison(apiDetail, tmp);
        if (!sameRow) {
            setShowDetails(true)
        } else {
            setShowDetails(!showDetails)
        }
        setApiDetail((prev) => {
            if (sameRow) {
                return prev;
            }
            return { ...tmp }
        })
    }

    function handleRefresh() {
        fetchData()
        func.setToast(true, false, "Endpoints refreshed")
    }

    async function exportOpenApi() {
        let lastFetchedUrl = null;
        let lastFetchedMethod = null;
        for (let index = 0; index < 10; index++) {
            let result = await api.downloadOpenApiFile(apiCollectionId, lastFetchedUrl, lastFetchedMethod)
            let openApiString = result["openAPIString"]
            let blob = new Blob([openApiString], {
                type: "application/json",
            });
            const fileName = "open_api_" + collectionsMap[apiCollectionId] + ".json";
            saveAs(blob, fileName);

            lastFetchedUrl = result["lastFetchedUrl"]
            lastFetchedMethod = result["lastFetchedMethod"]

            if (!lastFetchedUrl || !lastFetchedMethod) break;
        }
        func.setToast(true, false, "OpenAPI spec downloaded successfully")
    }

    function exportCsv() {
        if (!loading) {
            let headerTextToValueMap = Object.fromEntries(headers.map(x => [x.text, x.value]).filter(x => x[0].length > 0));

            let csv = Object.keys(headerTextToValueMap).join(",") + "\r\n"
            const allEndpoints = endpointData['All']
            allEndpoints.forEach(i => {
                csv += Object.values(headerTextToValueMap).map(h => (i[h] || "-")).join(",") + "\r\n"
            })
            let blob = new Blob([csv], {
                type: "application/csvcharset=UTF-8"
            });
            saveAs(blob, ("All endopints") + ".csv");
            func.setToast(true, false, "CSV exported successfully")
        }
    }

    async function exportPostman() {
        const result = await api.exportToPostman(apiCollectionId)
        if (result)
            func.setToast(true, false, "Postman collection downloaded successfully")
    }

    function disambiguateLabel(key, value) {
        switch (key) {
            case "parameterisedEndpoint":
                return func.convertToDisambiguateLabelObj(value, null, 1)
            case "method":
                return func.convertToDisambiguateLabelObj(value, null, 3)
            default:
              return func.convertToDisambiguateLabelObj(value, null, 2);
          }          
    }

    function handleFileChange(file) {
        if (file) {
            const reader = new FileReader();

            let isHar = file.name.endsWith(".har")
            if (isHar && file.size >= 52428800) {
                func.setToast(true, true, "Please limit the file size to less than 50 MB")
                return
            }
            let isJson = file.name.endsWith(".json")
            let isPcap = file.name.endsWith(".pcap")
            if (isHar || isJson) {
                reader.readAsText(file)
            } else if (isPcap) {
                reader.readAsArrayBuffer(new Blob([file]))
            }
            reader.onload = async () => {
                let skipKafka = false;//window.location.href.indexOf("http://localhost") != -1
                if (isHar) {
                    const formData = new FormData();
                    formData.append("harString", reader.result)
                    formData.append("hsFile", reader.result)
                    formData.append("skipKafka", skipKafka)
                    formData.append("apiCollectionId", apiCollectionId);
                    func.setToast(true, false, "We are uploading your har file, please dont refresh the page!")

                    api.uploadHarFile(formData).then(resp => {
                        if (file.size > 2097152) {
                            func.setToast(true, false, "We have successfully read your file")
                        }
                        else {
                            func.setToast(true, false, "Your Har file has been successfully processed")
                        }
                        fetchData()
                    }).catch(err => {
                        if (err.message.includes(404)) {
                            func.setToast(true, true, "Please limit the file size to less than 50 MB")
                        } else {
                            func.setToast(true, true, "Something went wrong while processing the file")
                        }
                    })

                } else if (isPcap) {
                    var arrayBuffer = reader.result
                    var bytes = new Uint8Array(arrayBuffer);

                    await api.uploadTcpFile([...bytes], apiCollectionId, skipKafka)
                }
            }
        }
    }

    function displayGPT(){
        setIsGptScreenActive(true)
        let requestObj = {key: "COLLECTION",filteredItems: filteredEndpoints,apiCollectionId: Number(apiCollectionId)}
        const activePrompts = dashboardFunc.getPrompts(requestObj)
        setPrompts(activePrompts)
    }
    const secondaryActionsComponent = (
        <HorizontalStack gap="2">

            <Popover 
                active={exportOpen}
                activator={(
                    <Button onClick={() => setExportOpen(true)} disclosure>
                        More Actions
                    </Button>
                )}
                autofocusTarget="first-node"
                onClose={() => { setExportOpen(false) }}
            >
                <Popover.Pane fixed>
                    <Popover.Section>
                        <VerticalStack gap={2}>
                            <div onClick={handleRefresh} style={{cursor: 'pointer'}}>
                                <Text fontWeight="regular" variant="bodyMd">Refresh</Text>
                            </div>
                            <UploadFile
                                fileFormat=".har"
                                fileChanged={file => handleFileChange(file)}
                                tooltipText="Upload traffic(.har)"
                                label={<Text fontWeight="regular" variant="bodyMd">Upload traffic</Text>}
                                primary={false} 
                            />
                        </VerticalStack>
                    </Popover.Section>
                    <Popover.Section>
                        <VerticalStack gap={2}>
                            <Text>Export as:</Text>
                                <VerticalStack gap={1}>
                                <div onClick={exportOpenApi} style={{cursor: 'pointer'}}>
                                    <Text fontWeight="regular" variant="bodyMd">OpenAPI spec</Text>
                                </div>
                                <div onClick={exportPostman} style={{cursor: 'pointer'}}>
                                    <Text fontWeight="regular" variant="bodyMd">Postman</Text>
                                </div>
                                <div onClick={exportCsv} style={{cursor: 'pointer'}}>
                                    <Text fontWeight="regular" variant="bodyMd">CSV</Text>
                                </div>
                            </VerticalStack>
                        </VerticalStack>
                    </Popover.Section>
                </Popover.Pane>
            </Popover>

            {isGptActive ? <Button onClick={displayGPT}>Ask AktoGPT</Button>: null}
                    
            <RunTest
                apiCollectionId={apiCollectionId}
                endpoints={filteredEndpoints}
                filtered={loading ? false : filteredEndpoints.length !== endpointData["All"].length}
            />
        </HorizontalStack>
    )

    const handleSelectedTab = (selectedIndex) => {
        setLoading(true)
        setSelected(selectedIndex)
        setTimeout(()=>{
            setLoading(false)
        },200)
    }

    const [showApiGroupModal, setShowApiGroupModal] = useState(false)
    const [apis, setApis] = useState([])
    const [actionOperation, setActionOperation] = useState(Operation.ADD)

    function handleApiGroupAction(selectedResources, operation){

        setActionOperation(operation)
        setApis(selectedResources)
        setShowApiGroupModal(true);
    }

    function toggleApiGroupModal(){
        setShowApiGroupModal(false);
    }

    const promotedBulkActions = (selectedResources) => [
        {
          content: 'Add to API group',
          onAction: () => handleApiGroupAction(selectedResources, Operation.ADD)
        },
        {
            content: 'Remove from API group',
            onAction: () => handleApiGroupAction(selectedResources, Operation.REMOVE)
        },
      ];

    return (
        <PageWithMultipleCards
            title={
                <Text variant='headingLg' truncate>{pageTitle}</Text>
            }
            backUrl="/dashboard/observe/inventory"
            secondaryActions={secondaryActionsComponent}
            components={
                loading ? [<SpinnerCentered key="loading" />] :
                    [
                        <div className="apiEndpointsTable" key="table">
                            <GithubSimpleTable
                                key="table"
                                pageLimit={50}
                                data={endpointData[selectedTab]}
                                sortOptions={sortOptions}
                                resourceName={resourceName}
                                filters={[]}
                                disambiguateLabel={disambiguateLabel}
                                headers={headers}
                                getStatus={() => { return "warning" }}
                                selected={selected}
                                onRowClick={handleRowClick}
                                onSelect={handleSelectedTab}
                                getFilteredItems={getFilteredItems}
                                mode={IndexFiltersMode.Default}
                                headings={headings}
                                useNewRow={true}
                                condensedHeight={true}
                                tableTabs={tableTabs}
                                selectable={true}
                                promotedBulkActions={promotedBulkActions}
                            />
                            <Modal large open={isGptScreenActive} onClose={()=> setIsGptScreenActive(false)} title="Akto GPT">
                                <Modal.Section flush>
                                    <AktoGptLayout prompts={prompts} closeModal={()=> setIsGptScreenActive(false)}/>
                                </Modal.Section>
                            </Modal>
                        </div>,
                        <ApiDetails
                            key="details"
                            showDetails={showDetails}
                            setShowDetails={setShowDetails}
                            apiDetail={apiDetail}
                            headers={transform.getDetailsHeaders()}
                            getStatus={() => { return "warning" }}
                            isGptActive={isGptActive}
                        />,
                        <ApiGroupModal
                            key="api-group-modal"
                            showApiGroupModal={showApiGroupModal}
                            toggleApiGroupModal={toggleApiGroupModal}
                            apis={apis}
                            operation={actionOperation}
                        />
                    ]}
        />
    )
}

export default ApiEndpoints

// apps/dashboard/web/src/apps/dashboard/views/observe/inventory/components/APIEndpoints.vue
<template>
    <spinner v-if="endpointsLoading" />
    <div class="pr-4 api-endpoints" v-else>
        <div>
            <div class="d-flex jc-end pb-3 pt-3">
                    <v-tooltip bottom>
                        <template v-slot:activator='{on, attrs}'>
                            <v-btn 
                                icon 
                                color="var(--themeColorDark)" 
                                @click="refreshPage(false)"
                                v-on="on"
                                v-bind="attrs"
                            >
                                    <v-icon>$fas_redo</v-icon>
                            </v-btn>
                        </template>
                        Refresh
                    </v-tooltip>

                <upload-file fileFormat=".har" @fileChanged="handleFileChange" tooltipText="Upload traffic (.har)" label="" type="uploadTraffic"/>
                <icon-menu icon="$fas_download" :items="downloadFileItems"/>
            </div>
        </div>
        <div class="d-flex">
            <count-box title="Sensitive Endpoints" :count="sensitiveEndpoints.length" colorTitle="Overdue"/>
            <count-box title="Undocumented Endpoints" :count="shadowEndpoints.length" colorTitle="Pending"/>
            <count-box title="Deprecated Endpoints" :count="unusedEndpoints.length" colorTitle="This week"/>
            <count-box title="All Endpoints" :count="allEndpoints.length" colorTitle="Total"/>
        </div> 
        
        <layout-with-tabs title="" :tabs="['All', 'Sensitive', 'Unauthenticated', 'Undocumented', 'Deprecated', 'Documented', 'Tests']">
            <template slot="actions-tray">
            </template>
            <template slot="All">
                <simple-table 
                    :headers=tableHeaders 
                    :items=allEndpoints 
                    @rowClicked=rowClicked 
                    @filterApplied="filterApplied"
                    name="All" 
                    sortKeyDefault="sensitiveTags" 
                    :sortDescDefault="true"
                >
                    <template #add-new-row-btn="{filteredItems}">
                        <div>
                            <secondary-button 
                                @click="showScheduleDialog(filteredItems)"
                                icon="$fas_play"
                                text="Run Test" 
                            />                            
                        </div>
                        
                    </template>
                    <template #item.sensitiveTags="{item}">
                        <sensitive-chip-group :sensitiveTags="Array.from(item.sensitiveTags || new Set())" />
                    </template>
                    <template #item.tags="{item}">
                        <tag-chip-group :tags="Array.from(item.tags || [])" />
                    </template>
                </simple-table>
            </template>
            <template slot="Sensitive">
                <simple-table 
                    :headers=tableHeaders 
                    :items=sensitiveEndpoints 
                    @rowClicked=rowClicked 
                    name="Sensitive"
                >
                    <template #item.sensitiveTags="{item}">
                        <sensitive-chip-group :sensitiveTags="Array.from(item.sensitiveTags || new Set())" />
                    </template>
                    <template #item.tags="{item}">
                        <tag-chip-group :tags="Array.from(item.tags || [])" />
                    </template>
                </simple-table>
            </template>
            <template slot="Undocumented">
                <simple-table 
                    :headers=tableHeaders 
                    :items=shadowEndpoints 
                    @rowClicked=rowClicked 
                    name="Undocumented"  
                    sortKeyDefault="sensitiveTags" 
                    :sortDescDefault="true"
                >
                    <template #item.sensitiveTags="{item}">
                        <sensitive-chip-group :sensitiveTags="Array.from(item.sensitiveTags || new Set())" />
                    </template>
                    <template #item.tags="{item}">
                        <tag-chip-group :tags="Array.from(item.tags || [])" />
                    </template>
                </simple-table>
            </template>
            <template slot="Deprecated">
                <simple-table 
                    :headers=unusedHeaders 
                    :items=deprecatedEndpoints
                    name="Deprecated"
                />
            </template>
            <template slot="Documented">
                <v-file-input
                    :rules=swaggerUploadRules
                    show-size
                    label="Upload JSON file"
                    prepend-icon="$curlyBraces"
                    accept=".json"
                    @change="handleSwaggerFileUpload"
                    v-model=swaggerFile
                ></v-file-input>
                <json-viewer
                    v-if="swaggerContent"
                    :contentJSON="swaggerContent"
                    :errors="{}"
                />
            </template>
            <template slot="Unauthenticated">
                <simple-table 
                    :headers=tableHeaders 
                    :items=openEndpoints
                    @rowClicked=rowClicked 
                    name="Unauthenticated" 
                    sortKeyDefault="sensitiveTags" 
                    :sortDescDefault="true"
                >
                    <template #item.sensitiveTags="{item}">
                        <sensitive-chip-group :sensitiveTags="Array.from(item.sensitiveTags || new Set())" />
                    </template>
                    <template #item.tags="{item}">
                        <tag-chip-group :tags="Array.from(item.tags || [])" />
                    </template>
                </simple-table>
            </template>
            <template slot="Tests">
                <div>
                    <div class="d-flex jc-end ma-2">
                        <v-btn v-if="!showWorkflowTestBuilder" primary dark color="var(--themeColor)" @click="() => {originalStateFromDb = null; showWorkflowTestBuilder = true}">
                            Create new workflow
                        </v-btn>
                        <div style="align-items: center; display: flex; padding-right: 12px ">
                          <upload-file fileFormat=".json" @fileChanged="handleFileChange" tooltipText="Upload workflow" label="" type="uploadWorkflow"/>
                        </div>
                    </div>
                    <simple-table 
                        v-if="!showWorkflowTestBuilder"
                        :headers="workflowTestHeaders" 
                        :items="workflowTests"
                        @rowClicked="item => {originalStateFromDb = item; showWorkflowTestBuilder = true}"
                        name="Deprecated"
                    />
                    <div
                        v-if="showWorkflowTestBuilder"
                        width="80%"
                    >
                        <v-btn icon primary dark color="var(--themeColor)" class="float-right" @click="() => {originalStateFromDb = null; showWorkflowTestBuilder = false}">
                            <v-icon>$fas_times</v-icon>
                        </v-btn>
                        <workflow-test-builder :endpointsList=allEndpoints :apiCollectionId="apiCollectionId" :originalStateFromDb="originalStateFromDb" :defaultOpenResult="false" class="white-background"/>
                    </div>
                    
                
                </div>
            </template>
        </layout-with-tabs>
        
        <v-dialog v-model="showTestSelectorDialog" width="800px"> 
            <tests-selector :collectionName="apiCollectionName" @testsSelected=startTest v-if="showTestSelectorDialog"/>
        </v-dialog>
    </div>
</template>

<script>
import CountBox from '@/apps/dashboard/shared/components/CountBox'
import { mapState } from 'vuex'
import func from "@/util/func"
import obj from "@/util/obj"
import constants from '@/util/constants'
import LayoutWithTabs from '@/apps/dashboard/layouts/LayoutWithTabs'
import SimpleTable from '@/apps/dashboard/shared/components/SimpleTable'
import api from '../api'
import SensitiveChipGroup from '@/apps/dashboard/shared/components/SensitiveChipGroup'
import TagChipGroup from '@/apps/dashboard/shared/components/TagChipGroup'
import Spinner from '@/apps/dashboard/shared/components/Spinner'
import { saveAs } from 'file-saver'
import UploadFile from '@/apps/dashboard/shared/components/UploadFile'
import JsonViewer from "@/apps/dashboard/shared/components/JSONViewer"
import IconMenu from '@/apps/dashboard/shared/components/IconMenu'
import WorkflowTestBuilder from './WorkflowTestBuilder'
import TestsSelector from './TestsSelector'
import SecondaryButton from '@/apps/dashboard/shared/components/buttons/SecondaryButton'

export default {
    name: "ApiEndpoints",
    components: { 
        CountBox, 
        LayoutWithTabs,
        SimpleTable,
        SensitiveChipGroup,
        TagChipGroup,
        Spinner,
        UploadFile,
        JsonViewer,
        IconMenu,
        WorkflowTestBuilder,
        TestsSelector,
        SecondaryButton,
    },
    props: {
        apiCollectionId: obj.numR
    },
    activated(){
        this.refreshPage(true)
    },
    data() {
        return {
            filteredItems: [],
            file: null,
            rules: [
                value => !value || value.size < 50e6 || 'HAR file size should be less than 50 MB!',
            ],
            swaggerUploadRules: [
                    value => !value || value.size < 2e6 || 'JSON file size should be less than 2 MB!',
                ],
            swaggerFile: null,
            showMenu: false,
            tableHeaders: [
                {
                    text: '',
                    value: 'color',
                    hideFilter: true
                },
                {
                    text: 'Endpoint',
                    value: 'parameterisedEndpoint'
                },
                {
                    text: 'Method',
                    value: 'method'
                },
                {
                    text: 'Tags',
                    value: 'tags'
                },
                {
                    text: 'Sensitive Params',
                    value: 'sensitiveTags'
                },
                {
                  text: 'Last Seen',
                  value: 'last_seen'
                },
                {
                  text: 'Access Type',
                  value: 'access_type'
                },
                {
                  text: 'Auth Type',
                  value: 'auth_type'
                },
                {
                    text: constants.DISCOVERED,
                    value: 'added'
                },
                {
                    text: 'Changes',
                    value: 'changes',
                    hideFilter: true
                }
            ],
            unusedHeaders: [
                {
                    text: '',
                    value: 'color'
                },                
                {
                    text: 'Endpoint',
                    value: 'endpoint'
                },
                {
                    text: 'Method',
                    value: 'method'
                },
                {
                    text: 'Last seen',
                    value: 'lastSeen'
                }
            ],
            downloadFileItems: [
                {
                    label: "Download OpenAPI Spec",
                    click: this.downloadOpenApiFile
                },
                {
                    label: "Export to Postman",
                    click: this.exportToPostman
                },
                {
                    label: "Download CSV file",
                    click: this.downloadData
                }
            ],
            prompts: [
                {
                    keyword: "Payment",
                },
                {
                    keyword: "User",
                },
                {
                    keyword: "Order",
                },
                {
                    keyword: "Product",
                },
                {
                    keyword: "Authentication",
                },
                {
                    keyword: "Login",           
                },
                {
                    keyword: "Search",                
                }   
            ],
            showTestSelectorDialog: false,
            filteredItemsForScheduleTest: [],
            workflowTestHeaders: [
                {
                    text: '',
                    value: 'color'
                },                
                {
                    text: 'Test',
                    value: 'id'
                },
                {
                    text: 'Author',
                    value: 'author'
                }
            ],
            showWorkflowTestBuilder: false,
            originalStateFromDb: null,
            workflowTests: [],
            showGPTPrompts:false,
            getResponse:false,
            promptText: "",
            responseArr:[],
        }
    },
    methods: {
        filterApplied(data) {
            this.filteredItems = data
            this.$store.commit('inventory/FILTERED_ITEMS', data)
        },
        rowClicked(row,$event) {
            this.$emit('selectedItem', {apiCollectionId: this.apiCollectionId || 0, urlAndMethod: row.endpoint + " " + row.method, type: 2},$event)
        },
        downloadData() {
            let headerTextToValueMap = Object.fromEntries(this.tableHeaders.map(x => [x.text, x.value]).filter(x => x[0].length > 0));

            let csv = Object.keys(headerTextToValueMap).join(",")+"\r\n"
            this.allEndpoints.forEach(i => {
                csv += Object.values(headerTextToValueMap).map(h => (i[h] || "-")).join(",") + "\r\n"
            })
            let blob = new Blob([csv], {
                type: "application/csvcharset=UTF-8"
            });
            saveAs(blob, (this.apiCollectionName || "All endopints") + ".csv");
        },
        prettifyDate(ts) {
            if (ts)
                return func.prettifyEpoch(ts)
            else
                return '-'
        },
        handleFileChange({file, type}) {
            if (!file) {
                this.content = null
            } else {
                var reader = new FileReader();
                
                // Use the javascript reader object to load the contents
                // of the file in the v-model prop
                
                let isHar = file.name.endsWith(".har")
                if(isHar && file.size >= 52428800){
                    window._AKTO.$emit('SHOW_SNACKBAR', {
                        show: true,
                        text: "Please limit the file size to less than 50 MB",
                        color: 'red'
                    })
                    return
                }
                let isJson = file.name.endsWith(".json")
                let isPcap = file.name.endsWith(".pcap")
                if (isHar || isJson) {
                    reader.readAsText(file)
                } else if (isPcap) {
                    reader.readAsArrayBuffer(new Blob([file]))
                }
                reader.onload = async () => {
                    let skipKafka = false;//window.location.href.indexOf("http://localhost") != -1
                    if (isHar) {
                        var formData = new FormData();
                        formData.append("harString", reader.result)
                        formData.append("hsFile", reader.result)
                        formData.append("skipKafka", skipKafka)
                        window._AKTO.$emit('SHOW_SNACKBAR', {
                            show: true,
                            text: "We are uploading your har file, please dont refresh the page!",
                            color: 'green'
                        })
                        this.$store.dispatch('inventory/uploadHarFile', { formData }).then(resp => {
                            if(file.size > 2097152){
                                window._AKTO.$emit('SHOW_SNACKBAR', {
                                    show: true,
                                    text: "We have successfully read your file, please refresh the page in a few mins to check your APIs",
                                    color: 'green'
                                })
                            }
                            else {
                                window._AKTO.$emit('SHOW_SNACKBAR', {
                                    show: true,
                                    text: "Your Har file has been successfully processed, please refresh the page to see your APIs",
                                    color: 'green'
                                })
                            }
                        }).catch(err => {
                            if(err.message.includes(404)){
                                window._AKTO.$emit('SHOW_SNACKBAR', {
                                    show: true,
                                    text: "Please limit the file size to less than 50 MB",
                                    color: 'red'
                                })
                            } else {
                                window._AKTO.$emit('SHOW_SNACKBAR', {
                                    show: true,
                                    text: "Something went wrong while processing the file",
                                    color: 'red'
                                })
                            }
                        })

                    } else if (isPcap) {
                        var arrayBuffer = reader.result
                        var bytes = new Uint8Array(arrayBuffer);

                        await api.uploadTcpFile([...bytes], this.apiCollectionId, skipKafka)
                    } else if (type === "uploadWorkflow") {
                        let resp = await this.$store.dispatch('inventory/uploadWorkflowJson', { content: reader.result, filename: file.name})
                        resp.workflowTests.forEach((x) => {
                          this.workflowTests.push({...x, color: "var(--white)"})
                        })
                    }
                }
            }
        },
        async downloadOpenApiFile() {
          let lastFetchedUrl = null;
          let lastFetchedMethod = null;
          for (let index =0; index < 10; index++) {
                var result = await this.$store.dispatch('inventory/downloadOpenApiFile', {lastFetchedUrl, lastFetchedMethod})
                let openApiString = result["openAPIString"]
                var blob = new Blob([openApiString], {
                    type: "application/json",
                });
                const fileName = "open_api_" +this.apiCollectionName+ ".json";
                saveAs(blob, fileName);

                lastFetchedUrl = result["lastFetchedUrl"]
                lastFetchedMethod = result["lastFetchedMethod"]

                if (!lastFetchedUrl || !lastFetchedMethod) break;
          }


          window._AKTO.$emit('SHOW_SNACKBAR', {
            show: true,
            text: "OpenAPI spec file downloaded !",
            color: 'green'
          })
        },

        async exportToPostman() {
          var result = await this.$store.dispatch('inventory/exportToPostman')
          window._AKTO.$emit('SHOW_SNACKBAR', {
            show: true,
            text: "Exported to Postman!",
            color: 'green'
          })
        },

      handleSwaggerFileUpload() {
            if (!this.swaggerFile) {this.swaggerContent = null}
            var reader = new FileReader();
            
            reader.readAsText(this.swaggerFile);
            reader.onload = () => {
                this.$store.dispatch('inventory/saveContent', { swaggerContent: JSON.parse(reader.result), filename: this.swaggerFile.name, apiCollectionId : this.apiCollectionId})
            }
        },
        async refreshPage(shouldLoad) {
            // if (!this.apiCollection || this.apiCollection.length === 0 || this.$store.state.inventory.apiCollectionId !== this.apiCollectionId) {
            this.showWorkflowTestBuilder = false
            let collectionIdChanged = this.$store.state.inventory.apiCollectionId !== this.apiCollectionId
            if (collectionIdChanged || !shouldLoad || ((new Date() / 1000) - this.lastFetched > 60*5)) {
                this.$store.dispatch('inventory/loadAPICollection', { apiCollectionId: this.apiCollectionId, shouldLoad: shouldLoad})
            }

            this.workflowTests = (await api.fetchWorkflowTests()).workflowTests.filter(x => x.apiCollectionId === this.apiCollectionId).map(x => {
                return {
                    ...x,
                    color: "var(--white)"
                }
            })

            this.$emit('mountedView', {type: 1, apiCollectionId: this.apiCollectionId})
        },
        showScheduleDialog(filteredItems) {
            this.showTestSelectorDialog = true
            this.filteredItemsForScheduleTest = filteredItems
        },
        toApiInfoKeyList(listEndpoints) {
            return listEndpoints.map(x => {
                return {
                    url: x.endpoint,
                    method: x.method,
                    apiCollectionId: x.apiCollectionId
                }
            })
        },
        async startTest({recurringDaily, startTimestamp, selectedTests, testName, testRunTime, maxConcurrentRequests, overriddenTestAppUrl, testRoleId}) {
            let apiInfoKeyList = this.toApiInfoKeyList(this.filteredItemsForScheduleTest)
            let filtersSelected = this.filteredItemsForScheduleTest.length === this.allEndpoints.length
            let store = this.$store
            let apiCollectionId = this.apiCollectionId
            
            if (filtersSelected) {
                await store.dispatch('testing/scheduleTestForCollection', {apiCollectionId, startTimestamp, recurringDaily, selectedTests, testName, testRunTime, maxConcurrentRequests, overriddenTestAppUrl, testRoleId})
            } else {
                await store.dispatch('testing/scheduleTestForCustomEndpoints', {apiInfoKeyList, startTimestamp, recurringDaily, selectedTests, testName, testRunTime, maxConcurrentRequests, overriddenTestAppUrl, source: "TESTING_UI", testRoleId})
            }
            
            this.showTestSelectorDialog = false            
        }      
    },
    computed: {
        ...mapState('inventory', ['apiCollection', 'endpointsLoading', 'swaggerContent', 'apiInfoList', 'filters', 'lastFetched', 'unusedEndpoints']),
        apiCollectionName() {
            return this.$store.state.collections.apiCollections.find(x => x.id === this.apiCollectionId).displayName
        },
        openEndpoints() {
          return this.allEndpoints.filter(x => x.open)
        },
        allEndpoints () {
            return func.mergeApiInfoAndApiCollection(this.apiCollection, this.apiInfoList)
        },
        sensitiveEndpoints() {
            return this.allEndpoints.filter(x => x.sensitive && x.sensitive.size > 0)
        },
        shadowEndpoints () {
            return this.allEndpoints.filter(x => x.shadow)
        },
        deprecatedEndpoints() {
            let ret = []
            this.apiInfoList.forEach(apiInfo => {
                if (apiInfo.lastSeen < (func.timeNow() - func.recencyPeriod)) {
                    ret.push({
                        endpoint: apiInfo.id.url, 
                        method: apiInfo.id.method,
                        lastSeen: func.prettifyEpoch(apiInfo.lastSeen),
                        color: func.actionItemColors()["This week"]
                    })
                }
            })

            try {
                this.unusedEndpoints.forEach((x) => {
                    if (!x) return;
                    let arr = x.split(" ");
                    if (arr.length < 2) return;
                    ret.push({
                      endpoint : arr[0],
                      method : arr[1],
                      color: func.actionItemColors()["This week"],
                      lastSeen: 'in API spec file'
                    })
                })
            } catch (e) {
            }
            return ret
        },
    },
    async mounted() {
        
    }
}
</script>

<style lang="sass" scoped>  
.api-endpoints
    & .table-column
        &:nth-child(1)    
            width: 4px
            min-width: 4px
            max-width: 4px
        &:nth-child(2)    
            width: 350px
            min-width: 350px
        &:nth-child(3)    
            width: 150px
            min-width: 150px
            max-width: 150px
        &:nth-child(4)    
            width: 250px
            min-width: 250px
            max-width: 250px
        &:nth-child(5)    
            width: 200px
            min-width: 200px
            max-width: 200px
        &:nth-child(6)    
            width: 200px
            min-width: 200px
            max-width: 200px
.menu
    display: flex
    justify-content: right
</style>
