// apps/dashboard/web/polaris_web/web/src/apps/dashboard/pages/quick_start/components/PostmanSource.jsx
import { Badge, Button, ButtonGroup, Checkbox, HorizontalStack, RadioButton, Text, VerticalStack, Modal, DescriptionList, Tooltip, Icon } from '@shopify/polaris'
import React, { useCallback, useEffect, useState } from 'react'
import Dropdown from '../../../components/layouts/Dropdown'
import settingFunctions from '../../settings/module'
import PasswordTextField from '../../../components/layouts/PasswordTextField';
import FileUpload from '../../../components/shared/FileUpload';
import {CancelMajor} from "@shopify/polaris-icons"
import api from '../api';
import Store from '../../../store';
import InformationBannerComponent from "./shared/InformationBannerComponent";
import SpinnerCentered from "../../../components/progress/SpinnerCentered"
import { QuestionMarkMinor } from "@shopify/polaris-icons"


function PostmanSource() {

    const [postmanKey, setPostmanKey] = useState('');
    const [workspaces, setWorkspaces] = useState([]);
    const [selected, setSelected] = useState('');
    const [loading, setLoading] = useState(false)
    const [showImportDetailsModal, setShowImportDetailsModal] = useState(false);
    const [uploadObj, setUploadObj] = useState({})
    const [importType, setImportType] = useState('ONLY_SUCCESSFUL_APIS');
    const [uploadId, setUploadId] = useState('');
    const [intervalId, setIntervalId] = useState(null);

    const setToastConfig = Store(state => state.setToastConfig)
    const setToast = (isActive, isError, message) => {
        setToastConfig({
          isActive: isActive,
          isError: isError,
          message: message
        })
    }

    const handleSelectChange = (id) =>{
        setSelected(id)
    }
    const handleChange = (val) => {
        setType(val)
    }
      
    async function fetchPostmanCred() {
        let postmanData = await settingFunctions.getPostmanCredentials();
        let postmanCred = postmanData.postmanCred
        if (postmanCred['api_key'] && postmanCred['workspace_id']) {
          setPostmanKey(postmanCred.api_key);
          setSelected(postmanCred.workspace_id);
          fetchWorkSpaces();
        }
    }
      
    async function fetchWorkSpaces() {
        if (postmanKey !== null && postmanKey.length > 0) {
          let allWorkSpaces = await settingFunctions.fetchPostmanWorkspaces(postmanKey);
          let arr = []
          allWorkSpaces.map((val)=>{
              let obj = {
                  label: val.name,
                  value: val.id
              }
              arr.push(obj)
          })
          setWorkspaces(arr);
        }
    }
    
    useEffect(()=> {
        fetchPostmanCred()
    },[])
      
    useEffect(() => {
        if(postmanKey && (postmanKey.length === 64 || postmanKey.length === 32)){
            fetchWorkSpaces()
        }
    }, [postmanKey]);

    const ApiKeySteps = [
        {
            text: "Open Postman. Click on Profile in the top-right corner of the screen."
        },
        {
            text: "From the drop-down menu, select 'Settings' and then 'API Keys'."
        },
        {
            text: "Click the 'Generate API Key' button. Copy the newly generated API key.",
        },
    ]

    const CollectionSteps = [
        {
            text: "Open Postman. Click on the collection you want to export from the left-hand sidebar."
        },
        {
            text: "Click the 'Export' button in the top-right corner of the screen."
        },
        {
            text: "Select the 'Collection v2.1' format and click export."
        }
    ]

    const [type, setType] = useState("api")
    const [allowResponses,setAllowResponses] = useState(true)
    const [files, setFiles] = useState(null)

    const toggleResponse = useCallback(newChecked => setAllowResponses(newChecked),[],);

    const apiActionComponent = (
        <div>
            <VerticalStack gap="1" >
                <span>4. Paste your postman key here: </span>
                <PasswordTextField setField={setPostmanKey} onFunc={true} field={postmanKey}/>
            </VerticalStack>
            <VerticalStack gap="1">
                <span>5. Select workspace you wish to import:  </span>
                <Dropdown menuItems={workspaces} selected={handleSelectChange} initial={selected}/>
            </VerticalStack>
        </div>
    )

    const setFilesCheck = (file) => {
        var reader = new FileReader()
        reader.readAsText(file)
        reader.onload = async () => {
            setFiles({content: reader.result, name: file.name})
        }
    }

    const collectionComponent = (
        <div>
            <VerticalStack gap="1">
                <span>4. Upload postman collection:</span>
                
                <HorizontalStack gap="2" >
                    {files ? 
                        <Badge size='medium' status='success'>
                            {files.name}
                            <Button icon={CancelMajor} plain onClick={() => setFiles(null)} />
                        </Badge> 
                    : null}
                    <FileUpload fileType="file" acceptString=".json" setSelectedFile={setFilesCheck} allowMultiple={false} allowedSize={20*1024*1024}/>
                </HorizontalStack>
            </VerticalStack>
        </div>
    )

    const importCollection = async() => {
        setLoading(true)
        await api.importPostmanWorkspace(selected,allowResponses,postmanKey).then((resp)=> {
            let uploadId = resp.uploadId;
            setLoading(false)
            setToast(true, false, "Workspace imported successfully")
            setShowImportDetailsModal(true);
            
            const id = setInterval(async () => {
                api.fetchPostmanImportLogs(uploadId).then(resp => {
                    if(resp.uploadDetails.uploadStatus === 'SUCCEEDED' || resp.uploadDetails.uploadStatus === 'FAILED'){
                        clearInterval(id);
                        setIntervalId(null);
                        setUploadObj(resp.uploadDetails);
                        if(resp.uploadDetails.uploadStatus === 'FAILED'){
                            setUploadId(uploadId);
                        }
                    }
                });
            }, 5000);
            setIntervalId(id);
        })
    }

    const uploadCollection = async() => {
        setLoading(true)
        await api.importDataFromPostmanFile(files.content, allowResponses).then((resp)=> {
            let uploadId = resp.uploadId;
            setLoading(false)
            setToast(true, false, "File uploaded successfully.")
            setShowImportDetailsModal(true);
            const id = setInterval(async () => {
                api.fetchPostmanImportLogs(uploadId).then(resp => {
                    if(resp.uploadDetails.uploadStatus === 'SUCCEEDED' || resp.uploadDetails.uploadStatus === 'FAILED'){
                        clearInterval(id);
                        setIntervalId(null);
                        setUploadObj(resp.uploadDetails);
                        if(resp.uploadDetails.uploadStatus === 'FAILED'){
                            setUploadId(uploadId);
                        }
                    }
                });
            }, 5000);
            setIntervalId(id);
        })
    }

    const toggleImport = (val) => {
        setImportType(val)
    }

    const startImport = async() => {
        setShowImportDetailsModal(false)
        setUploadObj({})
        api.ingestPostman(uploadObj.uploadId, importType).then(resp => {
            setToast(true, false, "File import has begun, refresh inventory page to view the postman collection")
        })
    }

    const closeModal = async() => {
        console.log("I am called")
        setShowImportDetailsModal(false)
        if(intervalId != null){
            clearInterval(this.intervalId)
            setIntervalId(null)
        }
        api.deleteImportedPostman(uploadObj.uploadId).then(resp => {
        })
        setUploadObj({})
    }


    let successModalContent = (
        <div>
            <Text>Total APIs in the {type==='api' ? 'selected workspace': 'uploaded file'}: {uploadObj.totalCount}</Text>
            <Text>Total apis parsed correctly by Akto: {uploadObj.correctlyParsedApis}</Text>
            {
                uploadObj.apisWithErrorsAndCannotBeImported + uploadObj.apisWithErrorsAndParsed > 0 &&
                <div>
                    <Text>Total apis parsed with errors by Akto (can still be imported): {uploadObj.apisWithErrorsAndParsed}</Text>
                    <Text>Total apis which cannot be imported: {uploadObj.apisWithErrorsAndCannotBeImported}</Text>
                    { uploadObj.apisWithErrorsAndParsed > 0 && 
                    <div>
                        <div style={{display: "flex"}}>
                            <RadioButton id="forceImport" label="Force import all APIs" checked={importType === "ALL_APIS"} onChange={()=>toggleImport("ALL_APIS")} />
                            <div style={{margin: "auto 12px"}}>
                                <Tooltip content={`We will import ${uploadObj.correctlyParsedApis + uploadObj.apisWithErrorsAndParsed} apis i.e. all the apis that have been correctly parsed and apis which have errors and can still be imported`} dismissOnMouseOut width="wide">
                                    <Icon source={QuestionMarkMinor} color="base" />
                                </Tooltip>
                            </div>
                        </div>
                        <div style={{display: "flex"}}>
                            <RadioButton id="successFulApis" label="Import only correctly formatted APIs" checked={importType === "ONLY_SUCCESSFUL_APIS"} onChange={()=>toggleImport("ONLY_SUCCESSFUL_APIS")}/>
                            <div style={{margin: "auto 12px"}}>
                                <Tooltip content={`We will import ${uploadObj.correctlyParsedApis} apis i.e. all the apis that have been correctly parsed only`} dismissOnMouseOut width="wide">
                                    <Icon source={QuestionMarkMinor} color="base" />
                                </Tooltip>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            }
            {uploadObj.collectionErrors > 0 && 
                <div>
                    {uploadObj.collectionErrors.forEach(error => {
                        <Text>{{error}}</Text>
                    })}
                </div>
            }
            {uploadObj.collectionErrors && uploadObj.collectionErrors.length > 0 &&
                <div>
                    <Text>Collection level errors</Text>
                    <DescriptionList
                        items={uploadObj.collectionErrors}
                    />
                </div>
            }

            {uploadObj.logs && uploadObj.logs.length > 0 &&
                <div>
                    <Text>Url level errors</Text>
                    <DescriptionList
                        items={uploadObj.logs}
                    />
                </div>
            }

                
            
        </div>
    )


    const steps = type === "api" ? ApiKeySteps: CollectionSteps
    const primaryAction = type === "api" ? importCollection: uploadCollection
    const primaryText = type === "api" ? "Import" : "Upload"
    
    const goToDocs = () => {
        window.open("https://docs.akto.io/traffic-connections/postman")
    }

    const buttonActive = ((type === "api" && workspaces.length > 0) || (type === "collection" && files)) 

    return (
        <div className='card-items'>
            <Text variant='bodyMd'>
                Use postman to send traffic to Akto and realize quick value. If you like what you see, we highly recommend using AWS or GCP traffic mirroring to get real user data for a smooth, automated and minimum false positive experience.
            </Text>

            <VerticalStack gap="1">
                <RadioButton id="api" label="Import using postman API key" checked={type === "api"} onChange={()=>handleChange("api")}/>
                <RadioButton id="collection" label="Import using postman collection file" checked={type === "collection"} onChange={()=>handleChange("collection")}/>
            </VerticalStack>
            <InformationBannerComponent docsUrl="https://docs.akto.io/traffic-connections/traffic-data-sources/postman#pre-requisites-for-akto-postman-connection"
                    content="Please ensure the pre-requisites " 
            />

            <VerticalStack gap="1">
                {steps.map((element,index) => (
                    <HorizontalStack gap="1" wrap={false} key={element.text}>
                        <span>{index + 1}.</span>
                        <span>{element.text}</span>
                    </HorizontalStack>
                ))}
                {type === "api" ? 
                   apiActionComponent
                    : collectionComponent
                }
            </VerticalStack>

            <VerticalStack gap="2">
                <Checkbox label="Allow Akto to replay API requests if responses are not found." checked={allowResponses} onChange={toggleResponse} />
                <ButtonGroup>
                    <Button onClick={primaryAction} primary disabled={!buttonActive} loading={loading}>{primaryText}</Button>
                    <Button onClick={goToDocs}>Go to docs</Button>
                </ButtonGroup>
                <ButtonGroup>
                    <Button plain onClick={(event) => { 
                                event.stopPropagation(); 
                                window.open('https://docs.akto.io/traffic-connections/traffic-data-sources/postman#troubleshooting-guide')
                            }}>postman trouble-shooting guide</Button>
                </ButtonGroup>
            </VerticalStack>
            <Modal
                open={showImportDetailsModal}
                onClose={() => {closeModal()}}
                title="Postman Import details"
                key="postman-import-details-modal"
                primaryAction={{
                    content: "Import",
                    onAction: startImport,
                    disabled: uploadObj.uploadStatus !== 'SUCCEEDED' || ( uploadObj.uploadStatus === 'SUCCEEDED' && (uploadObj.apisWithErrorsAndParsed + uploadObj.correctlyParsedApis === 0))
                }}
                secondaryActions={[
                    {
                        content: 'Cancel',
                        onAction: closeModal,
                    },
                ]}
            >
                <Modal.Section>
                    {uploadObj.uploadStatus === 'SUCCEEDED' ?
                        successModalContent
                    : uploadObj.uploadStatus === 'FAILED' ?
                    <Text>Something went wrong while processing this postman import. Please reach out to us at help@akto.io with the following uploadId: {uploadId} for further support.</Text> :
                    <div><Text>We are analyzing the postman file before we import it in Akto</Text><SpinnerCentered></SpinnerCentered></div>
                }
                </Modal.Section>
            </Modal>
        </div>
    )
}

export default PostmanSource

// apps/dashboard/web/src/apps/dashboard/views/quickstart/components/PostmanSource.vue
<template>
    <div>
        <div>
            Use postman to send traffic to Akto and realize quick value. If you like what you see, we highly recommend using AWS or GCP traffic mirroring to get real user data for a smooth, automated and minimum false positive experience.
        </div>
        <spinner v-if="loading" />
        <div v-else>
            <div>
                <v-radio-group v-model="uploadPostmanFile" row>
                    <v-radio
                        :value="0"
                        off-icon="$far_circle"
                        on-icon="$far_dot-circle"
                        :ripple="false"
                        class="radio"

                    >
                        <template slot="label">
                            <div class="radio-button-label">Import using Postman API Key</div>
                        </template>
                    </v-radio>
                    <v-radio
                        :value="1"
                        off-icon="$far_circle"
                        on-icon="$far_dot-circle"
                        :ripple="false"
                    >
                        <template slot="label">
                            <div class="radio-button-label">Import Postman collection file</div>
                        </template>
                    </v-radio>
                </v-radio-group>
                

                <div v-if="uploadPostmanFile === 0">
                    <step-builder :stepNumber="1">
                        <template slot="content">
                            <div>Open Postman. Click on Profile in the top-right corner of the screen.</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="2">
                        <template slot="content">
                            <div>From the drop-down menu, select "Settings" and then "API Keys."</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="3">
                        <template slot="content">
                            <div>Click the "Generate API Key" button. Copy the newly generated API key.</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="4">
                        <template slot="content">
                            <div>Paste Postman API key: </div>
                            <div style="width: 520px;" class="inline-text-field">
                                <v-text-field 
                                    height="13px" 
                                    v-model="postman_api_key" 
                                    :type="showKey? 'text' : 'password'"
                                    :append-icon="showKey ? '$fas_eye' : '$fas_eye-slash'"
                                    @click:append="showKey = !showKey"
                                />
                            </div>
                            <div class="postman-status">
                                <div v-if="this.workspace_loading" style="padding-left: 4px">
                                    <v-progress-circular indeterminate color="var(--lightGrey)" :size="12" :width="1.5"></v-progress-circular>
                                </div>
                                <div v-else>
                                    <div v-if="this.validApiKey && this.workspaces && this.workspaces.length>0">
                                        <v-icon color="var(--hexColor8)">$fas_check-circle</v-icon>
                                    </div>
                                    <div v-else>
                                        <v-icon color="var(--errorBtn)">$fas_times</v-icon>
                                    </div>
                                </div>
                            </div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="5">
                        <template slot="content">
                            <div>Select workspace you wish to import: </div>

                            <v-menu offset-y>
                                <template v-slot:activator="{ on, attrs }">
                                    <div style="width: 200px" class="inline-text-field">
                                        <v-text-field 
                                            height="14px" 
                                            :value="workspace ? workspace['name'] : null" 
                                            v-bind="attrs" 
                                            v-on="on"
                                            append-icon="$fas_angle-down"
                                            readonly
                                        />
                                    </div>
                                </template>
                                <v-list>
                                    <v-list-item v-for="(item, index) in this.workspaces" :key="index" @click="workspaceSelected(item)">
                                        <v-list-item-title class="options">{{ item['name']}}</v-list-item-title>
                                    </v-list-item>
                                </v-list>
                            </v-menu>

                            <span v-if="this.workspace_loading" style="padding-left: 4px">
                                <v-progress-circular indeterminate color="var(--lightGrey)" :size="12" :width="1.5"></v-progress-circular>
                            </span>
                            <span v-else>
                                <v-icon color="var(--hexColor8)" v-if="this.workspace">$fas_check-circle</v-icon>
                            </span>
                        </template>
                    </step-builder>
                </div>
                

                <div v-if="uploadPostmanFile === 1">
                    <step-builder :stepNumber="1">
                        <template slot="content">
                            <div>Open Postman. Click on the collection you want to export from the left-hand sidebar.</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="2">
                        <template slot="content">
                            <div>Click the "Export" button in the top-right corner of the screen.</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="3">
                        <template slot="content">
                            <div>Select the "Collection v2.1" format and click export.</div>
                        </template>
                    </step-builder>

                    <step-builder :stepNumber="4">
                        <template slot="content">
                            <div>Upload postman collection: </div>

                            <div v-if="this.file">
                                <v-chip
                                    class="ma-2"
                                    color="var(--themeColorDark)"
                                    text-color="white"
                                    small
                                >
                                    {{ file.name }}
                                    <v-icon @click="deletePostmanFile">$fas_times</v-icon>
                                </v-chip>
                            </div>

                            <upload-file fileFormat=".json" @fileChanged="handleFileChange" tooltipText="upload" label="" type="uploadTraffic"/>
                        </template>
                    </step-builder>
                </div>
            </div>

            <div class="mt-3">
                <div class="replay-div">
                    <v-checkbox
                        v-model="allowReplay"
                        on-icon="$far_check-square" off-icon="$far_square"
                        :ripple="false"
                        class="align-center justify-center"
                    />
                    Allow Akto to replay API requests if responses are not found.
                </div>
                <v-btn
                    color="var(--themeColor)"
                    @click="importPostmanWorkspace"
                    :disabled="!postman_setup_complete"
                    style="color:var(--white)">
                    {{ import_button }}
                </v-btn>
            </div>
        </div>
    </div>
</template>

<script>
import api from '../api.js'
import Spinner from '@/apps/dashboard/shared/components/Spinner'
import UploadFile from '@/apps/dashboard/shared/components/UploadFile'
import SimpleTextField from '@/apps/dashboard/shared/components/SimpleTextField'
import StepBuilder from '@/apps/dashboard/views/quickstart/components/StepBuilder'

export default {
    name: "PostmanSource",
    components: {
        Spinner,
        UploadFile,
        SimpleTextField,
        StepBuilder
    },
    data() {
        return {
            workspaces: [],
            workspace_id: null,
            workspace: null,
            workspace_loading: false,
            postman_api_key: "",
            loading: true,
            importing_workspace: false,
            uploadPostmanFile: 0,
            showKey: true,
            allowReplay: true,
            file: null
        }
    },
    mounted () {
        api.getPostmanCredentials().then((resp) => {
            this.loading = false;
            if (resp.postmanCred.api_key) {
                this.postman_api_key = resp.postmanCred.api_key
                this.workspace_id = resp.postmanCred.workspace_id
            }
        })
    },
    methods: {
        async fetchWorkspaces() {
            this.workspace_loading = true
            this.workspaces = []
            this.workspace = null
            let resp = await api.fetchPostmanWorkspaces(this.postman_api_key)

            let foundWorkspaces = resp.workspaces && resp.workspaces.length > 0;
            if(foundWorkspaces) {
                this.workspaces = resp.workspaces
                this.workspaces.forEach((x)=>{
                    if (x.id === this.workspace_id) {
                        this.workspace = x
                        this.validateWorkspace = 2
                    }
                })

                if (!this.workspace) {
                    this.workspace = this.workspaces[0]   
                }

            }

            this.workspace_loading = false
        },
        async importPostmanWorkspace(){
            this.importing_workspace = true;
            if (this.uploadPostmanFile === 0) {
                let resp = await api.importPostmanWorkspace(this.workspace['id'], this.allowReplay, this.postman_api_key);
            } else {
                console.log(this.file);
                let resp = await api.importDataFromPostmanFile(this.file['content'], this.allowReplay);
            }
            this.importing_workspace = false;
        },
        workspaceSelected(item) {
            this.workspace = item
            this.workspace_id = item['id']
        },
        deletePostmanFile() {
            this.file = null
        },
        handleFileChange({file, label, type}) {
            var reader = new FileReader();
            reader.readAsText(file)
            reader.onload = async () => {
                this.file = {"content": reader.result, "name": file['name']}
            }
        },
        validatePostmanApiKey(value) {
            return value && value.length === 64 
        }
    },
    computed: {
        validApiKey: function() {
            return this.validatePostmanApiKey(this.postman_api_key)
        },
        postman_setup_complete: function() {
            if (this.uploadPostmanFile === 0) {
                return this.postman_api_key && this.workspace
            } else {
                return Boolean(this.file)
            }
        },
        import_button: function() {
            return this.uploadPostmanFile === 0 ? "Import" : "Upload"
        }
    },
    watch: {
        postman_api_key(newValue, oldValue) {
            this.workspaces = []
            this.workspace = null
            if (!this.validatePostmanApiKey(newValue)) return
            this.fetchWorkspaces()
        }
    }
}
</script>

<style lang="sass" scoped>
.clickable-docs
    cursor: pointer
    color: var(--quickStartTheme) !important
    text-decoration: underline 

.replay-div
    display: flex
    align-items: center
    height: 40px

.radio-button-label
    font-weight: 800 !important
    font-size: 13px !important
    color: var(--hexColor19)

.postman-status
    height: 20px
    display: flex
    align-items: center
    padding-left: 4px

</style>

<style scoped>
.inline-text-field >>> .v-text-field .v-input__control .v-input__slot {
    margin: 0px 4px 0px 4px !important;
    color: var(--hexColor19) !important;
}

.inline-text-field >>> .v-text-field input {
    color: var(--hexColor19) !important;
    font-weight: 400 !important;
    font-size: 13px !important;
}

.inline-text-field >>> .v-text-field .v-input__append-inner, .v-text-field .v-input__prepend-inner {
    align-self: auto;
    display: inline-flex;
    margin-top: 0px;
    line-height: 0;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

div >>> .v-icon__component, .v-icon__svg {
    height: 12px;
    width: 12px;
}


</style>
